//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyDPDFull.refHermesLoc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Preadvice", Namespace="")]
    [System.SerializableAttribute()]
    public partial class Preadvice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessUnitCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashOnDeliveryCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CashOnDeliveryValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientParcelNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomStoragePeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAdditionalAddressInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAdditionalPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerApartmentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerBuildingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerConstructionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerFarthersNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerFrameNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerLandlinePhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerMobilePhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerStreetTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSubregionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectDistributionCenterCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DispatchDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlyDPDFull.refHermesLoc.ExtraParam[] ExtraParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuranceCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InsuranceValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OrderPlacementTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelBarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParcelHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParcelLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParcelWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParcelWidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelshopCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnDistributionCenterCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ServicesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessUnitCode {
            get {
                return this.BusinessUnitCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessUnitCodeField, value) != true)) {
                    this.BusinessUnitCodeField = value;
                    this.RaisePropertyChanged("BusinessUnitCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CashOnDeliveryCurrency {
            get {
                return this.CashOnDeliveryCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CashOnDeliveryCurrencyField, value) != true)) {
                    this.CashOnDeliveryCurrencyField = value;
                    this.RaisePropertyChanged("CashOnDeliveryCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CashOnDeliveryValue {
            get {
                return this.CashOnDeliveryValueField;
            }
            set {
                if ((this.CashOnDeliveryValueField.Equals(value) != true)) {
                    this.CashOnDeliveryValueField = value;
                    this.RaisePropertyChanged("CashOnDeliveryValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientOrderNumber {
            get {
                return this.ClientOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientOrderNumberField, value) != true)) {
                    this.ClientOrderNumberField = value;
                    this.RaisePropertyChanged("ClientOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientParcelNumber {
            get {
                return this.ClientParcelNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientParcelNumberField, value) != true)) {
                    this.ClientParcelNumberField = value;
                    this.RaisePropertyChanged("ClientParcelNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomStoragePeriod {
            get {
                return this.CustomStoragePeriodField;
            }
            set {
                if ((this.CustomStoragePeriodField.Equals(value) != true)) {
                    this.CustomStoragePeriodField = value;
                    this.RaisePropertyChanged("CustomStoragePeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAdditionalAddressInfo {
            get {
                return this.CustomerAdditionalAddressInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAdditionalAddressInfoField, value) != true)) {
                    this.CustomerAdditionalAddressInfoField = value;
                    this.RaisePropertyChanged("CustomerAdditionalAddressInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAdditionalPhoneNumber {
            get {
                return this.CustomerAdditionalPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAdditionalPhoneNumberField, value) != true)) {
                    this.CustomerAdditionalPhoneNumberField = value;
                    this.RaisePropertyChanged("CustomerAdditionalPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerApartmentNumber {
            get {
                return this.CustomerApartmentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerApartmentNumberField, value) != true)) {
                    this.CustomerApartmentNumberField = value;
                    this.RaisePropertyChanged("CustomerApartmentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerBuildingNumber {
            get {
                return this.CustomerBuildingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerBuildingNumberField, value) != true)) {
                    this.CustomerBuildingNumberField = value;
                    this.RaisePropertyChanged("CustomerBuildingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCity {
            get {
                return this.CustomerCityField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCityField, value) != true)) {
                    this.CustomerCityField = value;
                    this.RaisePropertyChanged("CustomerCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerConstructionNumber {
            get {
                return this.CustomerConstructionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerConstructionNumberField, value) != true)) {
                    this.CustomerConstructionNumberField = value;
                    this.RaisePropertyChanged("CustomerConstructionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCountryCode {
            get {
                return this.CustomerCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCountryCodeField, value) != true)) {
                    this.CustomerCountryCodeField = value;
                    this.RaisePropertyChanged("CustomerCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFarthersName {
            get {
                return this.CustomerFarthersNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerFarthersNameField, value) != true)) {
                    this.CustomerFarthersNameField = value;
                    this.RaisePropertyChanged("CustomerFarthersName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFirstName {
            get {
                return this.CustomerFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerFirstNameField, value) != true)) {
                    this.CustomerFirstNameField = value;
                    this.RaisePropertyChanged("CustomerFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFrameNumber {
            get {
                return this.CustomerFrameNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerFrameNumberField, value) != true)) {
                    this.CustomerFrameNumberField = value;
                    this.RaisePropertyChanged("CustomerFrameNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerLandlinePhoneNumber {
            get {
                return this.CustomerLandlinePhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerLandlinePhoneNumberField, value) != true)) {
                    this.CustomerLandlinePhoneNumberField = value;
                    this.RaisePropertyChanged("CustomerLandlinePhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerMobilePhoneNumber {
            get {
                return this.CustomerMobilePhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerMobilePhoneNumberField, value) != true)) {
                    this.CustomerMobilePhoneNumberField = value;
                    this.RaisePropertyChanged("CustomerMobilePhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNumber {
            get {
                return this.CustomerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNumberField, value) != true)) {
                    this.CustomerNumberField = value;
                    this.RaisePropertyChanged("CustomerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerRegion {
            get {
                return this.CustomerRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerRegionField, value) != true)) {
                    this.CustomerRegionField = value;
                    this.RaisePropertyChanged("CustomerRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerStreet {
            get {
                return this.CustomerStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerStreetField, value) != true)) {
                    this.CustomerStreetField = value;
                    this.RaisePropertyChanged("CustomerStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerStreetType {
            get {
                return this.CustomerStreetTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerStreetTypeField, value) != true)) {
                    this.CustomerStreetTypeField = value;
                    this.RaisePropertyChanged("CustomerStreetType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSubregion {
            get {
                return this.CustomerSubregionField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSubregionField, value) != true)) {
                    this.CustomerSubregionField = value;
                    this.RaisePropertyChanged("CustomerSubregion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSurname {
            get {
                return this.CustomerSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSurnameField, value) != true)) {
                    this.CustomerSurnameField = value;
                    this.RaisePropertyChanged("CustomerSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerZipCode {
            get {
                return this.CustomerZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerZipCodeField, value) != true)) {
                    this.CustomerZipCodeField = value;
                    this.RaisePropertyChanged("CustomerZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirectDistributionCenterCode {
            get {
                return this.DirectDistributionCenterCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectDistributionCenterCodeField, value) != true)) {
                    this.DirectDistributionCenterCodeField = value;
                    this.RaisePropertyChanged("DirectDistributionCenterCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DispatchDate {
            get {
                return this.DispatchDateField;
            }
            set {
                if ((this.DispatchDateField.Equals(value) != true)) {
                    this.DispatchDateField = value;
                    this.RaisePropertyChanged("DispatchDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlyDPDFull.refHermesLoc.ExtraParam[] ExtraParams {
            get {
                return this.ExtraParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraParamsField, value) != true)) {
                    this.ExtraParamsField = value;
                    this.RaisePropertyChanged("ExtraParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuranceCurrency {
            get {
                return this.InsuranceCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuranceCurrencyField, value) != true)) {
                    this.InsuranceCurrencyField = value;
                    this.RaisePropertyChanged("InsuranceCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InsuranceValue {
            get {
                return this.InsuranceValueField;
            }
            set {
                if ((this.InsuranceValueField.Equals(value) != true)) {
                    this.InsuranceValueField = value;
                    this.RaisePropertyChanged("InsuranceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderPlacementTimestamp {
            get {
                return this.OrderPlacementTimestampField;
            }
            set {
                if ((this.OrderPlacementTimestampField.Equals(value) != true)) {
                    this.OrderPlacementTimestampField = value;
                    this.RaisePropertyChanged("OrderPlacementTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelBarcode {
            get {
                return this.ParcelBarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelBarcodeField, value) != true)) {
                    this.ParcelBarcodeField = value;
                    this.RaisePropertyChanged("ParcelBarcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParcelHeight {
            get {
                return this.ParcelHeightField;
            }
            set {
                if ((this.ParcelHeightField.Equals(value) != true)) {
                    this.ParcelHeightField = value;
                    this.RaisePropertyChanged("ParcelHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParcelLength {
            get {
                return this.ParcelLengthField;
            }
            set {
                if ((this.ParcelLengthField.Equals(value) != true)) {
                    this.ParcelLengthField = value;
                    this.RaisePropertyChanged("ParcelLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParcelWeight {
            get {
                return this.ParcelWeightField;
            }
            set {
                if ((this.ParcelWeightField.Equals(value) != true)) {
                    this.ParcelWeightField = value;
                    this.RaisePropertyChanged("ParcelWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParcelWidth {
            get {
                return this.ParcelWidthField;
            }
            set {
                if ((this.ParcelWidthField.Equals(value) != true)) {
                    this.ParcelWidthField = value;
                    this.RaisePropertyChanged("ParcelWidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelshopCode {
            get {
                return this.ParcelshopCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelshopCodeField, value) != true)) {
                    this.ParcelshopCodeField = value;
                    this.RaisePropertyChanged("ParcelshopCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnDistributionCenterCode {
            get {
                return this.ReturnDistributionCenterCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnDistributionCenterCodeField, value) != true)) {
                    this.ReturnDistributionCenterCodeField = value;
                    this.RaisePropertyChanged("ReturnDistributionCenterCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Services {
            get {
                return this.ServicesField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicesField, value) != true)) {
                    this.ServicesField = value;
                    this.RaisePropertyChanged("Services");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtraParam", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ExtraParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreadviceResult", Namespace="http://schemas.datacontract.org/2004/07/B2C.API.DTO")]
    [System.SerializableAttribute()]
    public partial class PreadviceResult : OnlyDPDFull.refHermesLoc.RequestResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientParcelNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelBarcodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientParcelNumber {
            get {
                return this.ClientParcelNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientParcelNumberField, value) != true)) {
                    this.ClientParcelNumberField = value;
                    this.RaisePropertyChanged("ClientParcelNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelBarcode {
            get {
                return this.ParcelBarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelBarcodeField, value) != true)) {
                    this.ParcelBarcodeField = value;
                    this.RaisePropertyChanged("ParcelBarcode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestResult", Namespace="http://schemas.datacontract.org/2004/07/B2C.API.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlyDPDFull.refHermesLoc.StatusDateRangeResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlyDPDFull.refHermesLoc.ReturnInfoResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlyDPDFull.refHermesLoc.PreadviceResult))]
    public partial class RequestResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlyDPDFull.refHermesLoc.ErrorCode ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperationResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlyDPDFull.refHermesLoc.ErrorCode ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperationResult {
            get {
                return this.OperationResultField;
            }
            set {
                if ((this.OperationResultField.Equals(value) != true)) {
                    this.OperationResultField = value;
                    this.RaisePropertyChanged("OperationResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusDateRangeResult", Namespace="http://schemas.datacontract.org/2004/07/B2C.API.DTO")]
    [System.SerializableAttribute()]
    public partial class StatusDateRangeResult : OnlyDPDFull.refHermesLoc.RequestResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NextRequestDateFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlyDPDFull.refHermesLoc.Status[] StatusesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NextRequestDateFrom {
            get {
                return this.NextRequestDateFromField;
            }
            set {
                if ((this.NextRequestDateFromField.Equals(value) != true)) {
                    this.NextRequestDateFromField = value;
                    this.RaisePropertyChanged("NextRequestDateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlyDPDFull.refHermesLoc.Status[] Statuses {
            get {
                return this.StatusesField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusesField, value) != true)) {
                    this.StatusesField = value;
                    this.RaisePropertyChanged("Statuses");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnInfoResult", Namespace="http://schemas.datacontract.org/2004/07/B2C.API.DTO")]
    [System.SerializableAttribute()]
    public partial class ReturnInfoResult : OnlyDPDFull.refHermesLoc.RequestResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NextRequestDateFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlyDPDFull.refHermesLoc.ReturnInfo[] ReturnsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NextRequestDateFrom {
            get {
                return this.NextRequestDateFromField;
            }
            set {
                if ((this.NextRequestDateFromField.Equals(value) != true)) {
                    this.NextRequestDateFromField = value;
                    this.RaisePropertyChanged("NextRequestDateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlyDPDFull.refHermesLoc.ReturnInfo[] Returns {
            get {
                return this.ReturnsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnsField, value) != true)) {
                    this.ReturnsField = value;
                    this.RaisePropertyChanged("Returns");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCode", Namespace="http://schemas.datacontract.org/2004/07/B2C.API")]
    public enum ErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommonFail = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateParcelInfo = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteParcelInfo = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessUnitCodeIsNotFound = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoSufficientRights = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreadviceExists = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaxParcelCountPerRequest = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParcelBarcodeIsNotFound = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreadviceIsNotFound = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParcelShopCodeIsNotFound = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParcelBarcodeIsOutOfRange = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParcelBarcodeExists = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DistributionCenterCodeIsNotFound = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllBarcodesShouldBeEmpty = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllBarcodesAreRequired = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deserialization = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateParcelBarcode = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Range = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownStatus = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManagementStatus = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApplyStatus = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownStatusPartnerPointCode = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DistributionCenterCodeIsNotReferenced = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Duplicate = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductPriceNotFound = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownAddressType = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressCodeNotFound = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllowedValues = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaxIntervalReached = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessUnitIdIsNotFound = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnDistributionCenterCodeIsNotReferenced = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParcelBarcodeNotExists = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreadviceWasSentToDelivery = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StatusNewCanNotBeDeleted = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StatusNotFound = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrderNotFound = 48,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/B2C.API.DTO")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlyDPDFull.refHermesLoc.ExtraParam[] ExtraParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelBarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefuseReasonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefuseReasonSystemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StatusDeleteTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusSystemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatusTimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlyDPDFull.refHermesLoc.ExtraParam[] ExtraParams {
            get {
                return this.ExtraParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraParamsField, value) != true)) {
                    this.ExtraParamsField = value;
                    this.RaisePropertyChanged("ExtraParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelBarcode {
            get {
                return this.ParcelBarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelBarcodeField, value) != true)) {
                    this.ParcelBarcodeField = value;
                    this.RaisePropertyChanged("ParcelBarcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefuseReasonName {
            get {
                return this.RefuseReasonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RefuseReasonNameField, value) != true)) {
                    this.RefuseReasonNameField = value;
                    this.RaisePropertyChanged("RefuseReasonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefuseReasonSystemName {
            get {
                return this.RefuseReasonSystemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RefuseReasonSystemNameField, value) != true)) {
                    this.RefuseReasonSystemNameField = value;
                    this.RaisePropertyChanged("RefuseReasonSystemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StatusDeleteTimestamp {
            get {
                return this.StatusDeleteTimestampField;
            }
            set {
                if ((this.StatusDeleteTimestampField.Equals(value) != true)) {
                    this.StatusDeleteTimestampField = value;
                    this.RaisePropertyChanged("StatusDeleteTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusName {
            get {
                return this.StatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNameField, value) != true)) {
                    this.StatusNameField = value;
                    this.RaisePropertyChanged("StatusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusSystemName {
            get {
                return this.StatusSystemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusSystemNameField, value) != true)) {
                    this.StatusSystemNameField = value;
                    this.RaisePropertyChanged("StatusSystemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusTimestamp {
            get {
                return this.StatusTimestampField;
            }
            set {
                if ((this.StatusTimestampField.Equals(value) != true)) {
                    this.StatusTimestampField = value;
                    this.RaisePropertyChanged("StatusTimestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnInfo", Namespace="http://schemas.datacontract.org/2004/07/B2C.API.DTO")]
    [System.SerializableAttribute()]
    public partial class ReturnInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimBarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlyDPDFull.refHermesLoc.ExtraParam[] ExtraParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InsuranceValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelBarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelshopCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReturnTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WaybillNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimBarcode {
            get {
                return this.ClaimBarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimBarcodeField, value) != true)) {
                    this.ClaimBarcodeField = value;
                    this.RaisePropertyChanged("ClaimBarcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlyDPDFull.refHermesLoc.ExtraParam[] ExtraParams {
            get {
                return this.ExtraParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraParamsField, value) != true)) {
                    this.ExtraParamsField = value;
                    this.RaisePropertyChanged("ExtraParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InsuranceValue {
            get {
                return this.InsuranceValueField;
            }
            set {
                if ((this.InsuranceValueField.Equals(value) != true)) {
                    this.InsuranceValueField = value;
                    this.RaisePropertyChanged("InsuranceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelBarcode {
            get {
                return this.ParcelBarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelBarcodeField, value) != true)) {
                    this.ParcelBarcodeField = value;
                    this.RaisePropertyChanged("ParcelBarcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelshopCode {
            get {
                return this.ParcelshopCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelshopCodeField, value) != true)) {
                    this.ParcelshopCodeField = value;
                    this.RaisePropertyChanged("ParcelshopCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReturnTimestamp {
            get {
                return this.ReturnTimestampField;
            }
            set {
                if ((this.ReturnTimestampField.Equals(value) != true)) {
                    this.ReturnTimestampField = value;
                    this.RaisePropertyChanged("ReturnTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WaybillNumber {
            get {
                return this.WaybillNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.WaybillNumberField, value) != true)) {
                    this.WaybillNumberField = value;
                    this.RaisePropertyChanged("WaybillNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParcelShop", Namespace="http://schemas.datacontract.org/2004/07/B2C.API.DTO")]
    [System.SerializableAttribute()]
    public partial class ParcelShop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityCladrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlyDPDFull.refHermesLoc.ExtraParam[] ExtraParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxParcelOverallSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxParcelValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxParcelWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetroStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelShopCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelShopNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RailwayStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlyDPDFull.refHermesLoc.Schedule[] ScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ServicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdateTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressUrl {
            get {
                return this.AddressUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressUrlField, value) != true)) {
                    this.AddressUrlField = value;
                    this.RaisePropertyChanged("AddressUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityCladrCode {
            get {
                return this.CityCladrCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CityCladrCodeField, value) != true)) {
                    this.CityCladrCodeField = value;
                    this.RaisePropertyChanged("CityCladrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlyDPDFull.refHermesLoc.ExtraParam[] ExtraParams {
            get {
                return this.ExtraParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraParamsField, value) != true)) {
                    this.ExtraParamsField = value;
                    this.RaisePropertyChanged("ExtraParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxParcelOverallSize {
            get {
                return this.MaxParcelOverallSizeField;
            }
            set {
                if ((this.MaxParcelOverallSizeField.Equals(value) != true)) {
                    this.MaxParcelOverallSizeField = value;
                    this.RaisePropertyChanged("MaxParcelOverallSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxParcelValue {
            get {
                return this.MaxParcelValueField;
            }
            set {
                if ((this.MaxParcelValueField.Equals(value) != true)) {
                    this.MaxParcelValueField = value;
                    this.RaisePropertyChanged("MaxParcelValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxParcelWeight {
            get {
                return this.MaxParcelWeightField;
            }
            set {
                if ((this.MaxParcelWeightField.Equals(value) != true)) {
                    this.MaxParcelWeightField = value;
                    this.RaisePropertyChanged("MaxParcelWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetroStation {
            get {
                return this.MetroStationField;
            }
            set {
                if ((object.ReferenceEquals(this.MetroStationField, value) != true)) {
                    this.MetroStationField = value;
                    this.RaisePropertyChanged("MetroStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelShopCode {
            get {
                return this.ParcelShopCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelShopCodeField, value) != true)) {
                    this.ParcelShopCodeField = value;
                    this.RaisePropertyChanged("ParcelShopCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelShopName {
            get {
                return this.ParcelShopNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelShopNameField, value) != true)) {
                    this.ParcelShopNameField = value;
                    this.RaisePropertyChanged("ParcelShopName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentType {
            get {
                return this.PaymentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentTypeField, value) != true)) {
                    this.PaymentTypeField = value;
                    this.RaisePropertyChanged("PaymentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RailwayStation {
            get {
                return this.RailwayStationField;
            }
            set {
                if ((object.ReferenceEquals(this.RailwayStationField, value) != true)) {
                    this.RailwayStationField = value;
                    this.RaisePropertyChanged("RailwayStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlyDPDFull.refHermesLoc.Schedule[] Schedule {
            get {
                return this.ScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleField, value) != true)) {
                    this.ScheduleField = value;
                    this.RaisePropertyChanged("Schedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Services {
            get {
                return this.ServicesField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicesField, value) != true)) {
                    this.ServicesField = value;
                    this.RaisePropertyChanged("Services");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateTimestamp {
            get {
                return this.UpdateTimestampField;
            }
            set {
                if ((this.UpdateTimestampField.Equals(value) != true)) {
                    this.UpdateTimestampField = value;
                    this.RaisePropertyChanged("UpdateTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Schedule", Namespace="http://schemas.datacontract.org/2004/07/B2C.API.DTO")]
    [System.SerializableAttribute()]
    public partial struct Schedule : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlyDPDFull.refHermesLoc.TimeInterval[] TimeIntervalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DayOfWeek WeekDayField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlyDPDFull.refHermesLoc.TimeInterval[] TimeIntervals {
            get {
                return this.TimeIntervalsField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeIntervalsField, value) != true)) {
                    this.TimeIntervalsField = value;
                    this.RaisePropertyChanged("TimeIntervals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DayOfWeek WeekDay {
            get {
                return this.WeekDayField;
            }
            set {
                if ((this.WeekDayField.Equals(value) != true)) {
                    this.WeekDayField = value;
                    this.RaisePropertyChanged("WeekDay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeInterval", Namespace="http://schemas.datacontract.org/2004/07/B2C.API.DTO")]
    [System.SerializableAttribute()]
    public partial struct TimeInterval : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlyDPDFull.refHermesLoc.DayTime FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlyDPDFull.refHermesLoc.DayTime ToField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlyDPDFull.refHermesLoc.DayTime From {
            get {
                return this.FromField;
            }
            set {
                if ((this.FromField.Equals(value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlyDPDFull.refHermesLoc.DayTime To {
            get {
                return this.ToField;
            }
            set {
                if ((this.ToField.Equals(value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DayTime", Namespace="http://schemas.datacontract.org/2004/07/B2C.API.DTO")]
    [System.SerializableAttribute()]
    public partial struct DayTime : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte HoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte MinutesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Hours {
            get {
                return this.HoursField;
            }
            set {
                if ((this.HoursField.Equals(value) != true)) {
                    this.HoursField = value;
                    this.RaisePropertyChanged("Hours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Minutes {
            get {
                return this.MinutesField;
            }
            set {
                if ((this.MinutesField.Equals(value) != true)) {
                    this.MinutesField = value;
                    this.RaisePropertyChanged("Minutes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.hermes-dpd.ru/WS/", ConfigurationName="refHermesLoc.IWebService")]
    public interface IWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/CreatePreadvice", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/CreatePreadviceResponse")]
        OnlyDPDFull.refHermesLoc.PreadviceResult[] CreatePreadvice(OnlyDPDFull.refHermesLoc.Preadvice[] preadvices);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/CreatePreadvice", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/CreatePreadviceResponse")]
        System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.PreadviceResult[]> CreatePreadviceAsync(OnlyDPDFull.refHermesLoc.Preadvice[] preadvices);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/UpdatePreadvice", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/UpdatePreadviceResponse")]
        OnlyDPDFull.refHermesLoc.PreadviceResult[] UpdatePreadvice(OnlyDPDFull.refHermesLoc.Preadvice[] preadvices);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/UpdatePreadvice", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/UpdatePreadviceResponse")]
        System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.PreadviceResult[]> UpdatePreadviceAsync(OnlyDPDFull.refHermesLoc.Preadvice[] preadvices);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/DeletePreadvice", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/DeletePreadviceResponse")]
        OnlyDPDFull.refHermesLoc.PreadviceResult[] DeletePreadvice(string[] parcelBarcodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/DeletePreadvice", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/DeletePreadviceResponse")]
        System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.PreadviceResult[]> DeletePreadviceAsync(string[] parcelBarcodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/GetPreadvices", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/GetPreadvicesResponse")]
        OnlyDPDFull.refHermesLoc.Preadvice[] GetPreadvices(string businessUnitCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/GetPreadvices", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/GetPreadvicesResponse")]
        System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.Preadvice[]> GetPreadvicesAsync(string businessUnitCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/SendPreadvicesToDelivery", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/SendPreadvicesToDeliveryResponse")]
        OnlyDPDFull.refHermesLoc.PreadviceResult[] SendPreadvicesToDelivery(string[] parcelBarcodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/SendPreadvicesToDelivery", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/SendPreadvicesToDeliveryResponse")]
        System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.PreadviceResult[]> SendPreadvicesToDeliveryAsync(string[] parcelBarcodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/SendAllPreadvicesToDelivery", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/SendAllPreadvicesToDeliveryResponse")]
        OnlyDPDFull.refHermesLoc.PreadviceResult[] SendAllPreadvicesToDelivery(string businessUnitCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/SendAllPreadvicesToDelivery", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/SendAllPreadvicesToDeliveryResponse")]
        System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.PreadviceResult[]> SendAllPreadvicesToDeliveryAsync(string businessUnitCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/GetParcelShops", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/GetParcelShopsResponse")]
        OnlyDPDFull.refHermesLoc.ParcelShop[] GetParcelShops(string businessUnitCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/GetParcelShops", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/GetParcelShopsResponse")]
        System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.ParcelShop[]> GetParcelShopsAsync(string businessUnitCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/GetStatusesByBusinessUnit", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/GetStatusesByBusinessUnitResponse")]
        OnlyDPDFull.refHermesLoc.StatusDateRangeResult GetStatusesByBusinessUnit(string businessUnitCode, System.DateTime dateFrom, System.Nullable<System.DateTime> dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/GetStatusesByBusinessUnit", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/GetStatusesByBusinessUnitResponse")]
        System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.StatusDateRangeResult> GetStatusesByBusinessUnitAsync(string businessUnitCode, System.DateTime dateFrom, System.Nullable<System.DateTime> dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/GetStatusesByParcelBarcodes", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/GetStatusesByParcelBarcodesResponse")]
        OnlyDPDFull.refHermesLoc.Status[] GetStatusesByParcelBarcodes(string[] parcelBarCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/GetStatusesByParcelBarcodes", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/GetStatusesByParcelBarcodesResponse")]
        System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.Status[]> GetStatusesByParcelBarcodesAsync(string[] parcelBarCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/GetReturnInfoByBusinessUnit", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/GetReturnInfoByBusinessUnitResponse")]
        OnlyDPDFull.refHermesLoc.ReturnInfoResult GetReturnInfoByBusinessUnit(string businessUnitCode, System.DateTime dateFrom, System.Nullable<System.DateTime> dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.hermes-dpd.ru/WS/IWebService/GetReturnInfoByBusinessUnit", ReplyAction="https://api.hermes-dpd.ru/WS/IWebService/GetReturnInfoByBusinessUnitResponse")]
        System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.ReturnInfoResult> GetReturnInfoByBusinessUnitAsync(string businessUnitCode, System.DateTime dateFrom, System.Nullable<System.DateTime> dateTo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceChannel : OnlyDPDFull.refHermesLoc.IWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceClient : System.ServiceModel.ClientBase<OnlyDPDFull.refHermesLoc.IWebService>, OnlyDPDFull.refHermesLoc.IWebService {
        
        public WebServiceClient() {
        }
        
        public WebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlyDPDFull.refHermesLoc.PreadviceResult[] CreatePreadvice(OnlyDPDFull.refHermesLoc.Preadvice[] preadvices) {
            return base.Channel.CreatePreadvice(preadvices);
        }
        
        public System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.PreadviceResult[]> CreatePreadviceAsync(OnlyDPDFull.refHermesLoc.Preadvice[] preadvices) {
            return base.Channel.CreatePreadviceAsync(preadvices);
        }
        
        public OnlyDPDFull.refHermesLoc.PreadviceResult[] UpdatePreadvice(OnlyDPDFull.refHermesLoc.Preadvice[] preadvices) {
            return base.Channel.UpdatePreadvice(preadvices);
        }
        
        public System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.PreadviceResult[]> UpdatePreadviceAsync(OnlyDPDFull.refHermesLoc.Preadvice[] preadvices) {
            return base.Channel.UpdatePreadviceAsync(preadvices);
        }
        
        public OnlyDPDFull.refHermesLoc.PreadviceResult[] DeletePreadvice(string[] parcelBarcodes) {
            return base.Channel.DeletePreadvice(parcelBarcodes);
        }
        
        public System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.PreadviceResult[]> DeletePreadviceAsync(string[] parcelBarcodes) {
            return base.Channel.DeletePreadviceAsync(parcelBarcodes);
        }
        
        public OnlyDPDFull.refHermesLoc.Preadvice[] GetPreadvices(string businessUnitCode) {
            return base.Channel.GetPreadvices(businessUnitCode);
        }
        
        public System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.Preadvice[]> GetPreadvicesAsync(string businessUnitCode) {
            return base.Channel.GetPreadvicesAsync(businessUnitCode);
        }
        
        public OnlyDPDFull.refHermesLoc.PreadviceResult[] SendPreadvicesToDelivery(string[] parcelBarcodes) {
            return base.Channel.SendPreadvicesToDelivery(parcelBarcodes);
        }
        
        public System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.PreadviceResult[]> SendPreadvicesToDeliveryAsync(string[] parcelBarcodes) {
            return base.Channel.SendPreadvicesToDeliveryAsync(parcelBarcodes);
        }
        
        public OnlyDPDFull.refHermesLoc.PreadviceResult[] SendAllPreadvicesToDelivery(string businessUnitCode) {
            return base.Channel.SendAllPreadvicesToDelivery(businessUnitCode);
        }
        
        public System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.PreadviceResult[]> SendAllPreadvicesToDeliveryAsync(string businessUnitCode) {
            return base.Channel.SendAllPreadvicesToDeliveryAsync(businessUnitCode);
        }
        
        public OnlyDPDFull.refHermesLoc.ParcelShop[] GetParcelShops(string businessUnitCode) {
            return base.Channel.GetParcelShops(businessUnitCode);
        }
        
        public System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.ParcelShop[]> GetParcelShopsAsync(string businessUnitCode) {
            return base.Channel.GetParcelShopsAsync(businessUnitCode);
        }
        
        public OnlyDPDFull.refHermesLoc.StatusDateRangeResult GetStatusesByBusinessUnit(string businessUnitCode, System.DateTime dateFrom, System.Nullable<System.DateTime> dateTo) {
            return base.Channel.GetStatusesByBusinessUnit(businessUnitCode, dateFrom, dateTo);
        }
        
        public System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.StatusDateRangeResult> GetStatusesByBusinessUnitAsync(string businessUnitCode, System.DateTime dateFrom, System.Nullable<System.DateTime> dateTo) {
            return base.Channel.GetStatusesByBusinessUnitAsync(businessUnitCode, dateFrom, dateTo);
        }
        
        public OnlyDPDFull.refHermesLoc.Status[] GetStatusesByParcelBarcodes(string[] parcelBarCodes) {
            return base.Channel.GetStatusesByParcelBarcodes(parcelBarCodes);
        }
        
        public System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.Status[]> GetStatusesByParcelBarcodesAsync(string[] parcelBarCodes) {
            return base.Channel.GetStatusesByParcelBarcodesAsync(parcelBarCodes);
        }
        
        public OnlyDPDFull.refHermesLoc.ReturnInfoResult GetReturnInfoByBusinessUnit(string businessUnitCode, System.DateTime dateFrom, System.Nullable<System.DateTime> dateTo) {
            return base.Channel.GetReturnInfoByBusinessUnit(businessUnitCode, dateFrom, dateTo);
        }
        
        public System.Threading.Tasks.Task<OnlyDPDFull.refHermesLoc.ReturnInfoResult> GetReturnInfoByBusinessUnitAsync(string businessUnitCode, System.DateTime dateFrom, System.Nullable<System.DateTime> dateTo) {
            return base.Channel.GetReturnInfoByBusinessUnitAsync(businessUnitCode, dateFrom, dateTo);
        }
    }
}
